version: '3.8'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.9.0
    ports:
     - 9200:9200
     - 9300:9300
    networks:
      elastic:
    # volumes:
    #  - /usr/share/data/elasticsearch:/usr/share/elasticsearch/data
    environment:
     - discovery.type=single-node
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - TZ=Asia/Seoul
    user: root
    restart: always
    privileged: true

  kibana:
    container_name: kibana
    image: kibana:7.9.0
    ports:
     - 5601:5601
    networks:
      elastic:
    environment:
     ELASTICSERCH_UTL: http://elasticsearch:9200
     ELASTICSEARCH_HOSTS: http://elasticsearch:9200
     TZ: Asia/Seoul
    restart: always
    privileged: true
    platform: linux/x86_64

networks:
  elastic:

